-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.area
(
    idarea serial NOT NULL,
    area text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    CONSTRAINT "PK_78cd173450c37a9351b0f8efd5e" PRIMARY KEY (idarea)
);

CREATE TABLE IF NOT EXISTS public.areacentro
(
    idareacentro serial NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    area integer,
    centro integer,
    CONSTRAINT "PK_cd11f3040c1900447a3b2ab12d4" PRIMARY KEY (idareacentro)
);

CREATE TABLE IF NOT EXISTS public.categoriamaterial
(
    idcategoriamaterial serial NOT NULL,
    "códigomaterial" text COLLATE pg_catalog."default" NOT NULL,
    categoria text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    CONSTRAINT "PK_54390558abe7348a4790b02f7cb" PRIMARY KEY (idcategoriamaterial)
);

CREATE TABLE IF NOT EXISTS public.centro
(
    idcentro serial NOT NULL,
    centro text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    municipio integer,
    CONSTRAINT "PK_e8293b0865f1c26a8f31f1baaf0" PRIMARY KEY (idcentro)
);

CREATE TABLE IF NOT EXISTS public.detalles
(
    iddetalle serial NOT NULL,
    cantidasolicitada integer NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    material integer,
    personaaprueba integer,
    personaencargada integer,
    personasolicita integer,
    CONSTRAINT "PK_9989548e1a071c4637a1a969a02" PRIMARY KEY (iddetalle)
);

CREATE TABLE IF NOT EXISTS public.ficha
(
    idficha serial NOT NULL,
    numficha integer NOT NULL,
    cantidadaprendices integer,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    CONSTRAINT "PK_1023a71c3ea995a173165857011" PRIMARY KEY (idficha)
);

CREATE TABLE IF NOT EXISTS public.material
(
    idmaterial serial NOT NULL,
    nombrematerial text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    stock integer NOT NULL,
    caduca boolean NOT NULL,
    fechavencimiento timestamp without time zone,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    categoriamaterial integer,
    tipomaterial integer,
    unidadmedida integer,
    CONSTRAINT "PK_faf367bf6c36a6cb30a849c8fb7" PRIMARY KEY (idmaterial)
);

CREATE TABLE IF NOT EXISTS public.modulos
(
    id serial NOT NULL,
    nombre_modulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_ba8d97b7acc232a928b1d686c5f" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.movimiento
(
    idmovimiento serial NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    movimientopersona integer,
    tipomovimiento integer,
    CONSTRAINT "PK_38bb7afbe102f443429d85f928f" PRIMARY KEY (idmovimiento)
);

CREATE TABLE IF NOT EXISTS public.municipio
(
    idmunicipio serial NOT NULL,
    municipio text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    CONSTRAINT "PK_9288f1d12a5d8150c355b5e9b16" PRIMARY KEY (idmunicipio)
);

CREATE TABLE IF NOT EXISTS public.opciones
(
    id serial NOT NULL,
    nombre_opcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    ruta_frontend character varying(150) COLLATE pg_catalog."default" NOT NULL,
    id_modulo integer NOT NULL,
    CONSTRAINT "PK_dea3c16bc97a290f52a9428520b" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permiso
(
    idpermiso serial NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    codigo text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    id_opcion integer,
    CONSTRAINT "PK_183fafd22bdbf9043382b740ce0" PRIMARY KEY (idpermiso),
    CONSTRAINT "UQ_70a3960f3bb071a0eea3ea307bf" UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.persona
(
    idpersona serial NOT NULL,
    identificacion text COLLATE pg_catalog."default" NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    apellido text COLLATE pg_catalog."default" NOT NULL,
    telefono text COLLATE pg_catalog."default",
    correo text COLLATE pg_catalog."default" NOT NULL,
    contrasena text COLLATE pg_catalog."default" NOT NULL,
    edad integer NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    ficha integer,
    rol integer,
    CONSTRAINT "PK_5275574bb53a53ae56d8812b091" PRIMARY KEY (idpersona),
    CONSTRAINT "UQ_6150bc0608b585b62f23c4dfd86" UNIQUE (correo),
    CONSTRAINT "UQ_cd9577a78e7334321f9abc96cb4" UNIQUE (identificacion)
);

CREATE TABLE IF NOT EXISTS public.rol
(
    idrol serial NOT NULL,
    nombrerol text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    "permisosIdpermiso" integer,
    CONSTRAINT "PK_654858cf0914fbd65b6f01e22a2" PRIMARY KEY (idrol)
);

CREATE TABLE IF NOT EXISTS public.rol_permiso_opcion
(
    id serial NOT NULL,
    id_rol integer,
    id_permiso integer,
    id_opcion integer,
    CONSTRAINT "PK_d4082490ee8659e0607e42bbc85" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sede
(
    idsede serial NOT NULL,
    sede text COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    centro integer,
    CONSTRAINT "PK_f9eb6907d5dd48558b8a6135c38" PRIMARY KEY (idsede)
);

CREATE TABLE IF NOT EXISTS public.sitio
(
    idsitio serial NOT NULL,
    sitio text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    tipositio integer,
    CONSTRAINT "PK_cb67fe8eb3c75213bc3dfb9f1de" PRIMARY KEY (idsitio)
);

CREATE TABLE IF NOT EXISTS public.tipomaterial
(
    idtipomaterial serial NOT NULL,
    tipo text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    CONSTRAINT "PK_1f4aa631076d5b6c52f3bdfe228" PRIMARY KEY (idtipomaterial)
);

CREATE TABLE IF NOT EXISTS public.tipomovimiento
(
    idtipomovimiento serial NOT NULL,
    tipomovimiento text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    CONSTRAINT "PK_95db306a0154f43b64be382aca0" PRIMARY KEY (idtipomovimiento)
);

CREATE TABLE IF NOT EXISTS public.tipositio
(
    idtipositio serial NOT NULL,
    tipositio text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    CONSTRAINT "PK_9cce6859597dd4620600bd19d41" PRIMARY KEY (idtipositio)
);

CREATE TABLE IF NOT EXISTS public.titulado
(
    idtitulado serial NOT NULL,
    titulado text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    area integer,
    ficha integer,
    CONSTRAINT "PK_30a2ae3be3a2400f978c96c2bb9" PRIMARY KEY (idtitulado)
);

CREATE TABLE IF NOT EXISTS public.unidadmedida
(
    idunidadmedida serial NOT NULL,
    unidadmedida text COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fechacreacion timestamp without time zone DEFAULT now(),
    "fechaactualización" timestamp without time zone,
    CONSTRAINT "PK_9a8bf8df09fa5c7696070f913eb" PRIMARY KEY (idunidadmedida)
);

ALTER TABLE IF EXISTS public.areacentro
    ADD CONSTRAINT "FK_05fe98b4bd53f55e39e9e39d716" FOREIGN KEY (centro)
    REFERENCES public.centro (idcentro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.areacentro
    ADD CONSTRAINT "FK_9b107c077cc5e003120bf65f4b1" FOREIGN KEY (area)
    REFERENCES public.area (idarea) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.centro
    ADD CONSTRAINT "FK_cbe5b3653089f2d566e010dfcdf" FOREIGN KEY (municipio)
    REFERENCES public.municipio (idmunicipio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles
    ADD CONSTRAINT "FK_490b8696d80879896e68eacdc61" FOREIGN KEY (material)
    REFERENCES public.material (idmaterial) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles
    ADD CONSTRAINT "FK_57d79ec86f66a49effecaff282d" FOREIGN KEY (personaaprueba)
    REFERENCES public.persona (idpersona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles
    ADD CONSTRAINT "FK_80b4c82f96fad55456c51dac0bc" FOREIGN KEY (personaencargada)
    REFERENCES public.persona (idpersona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles
    ADD CONSTRAINT "FK_ffeccbfd18dc9cf6eb02588c78c" FOREIGN KEY (personasolicita)
    REFERENCES public.persona (idpersona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.material
    ADD CONSTRAINT "FK_6695492217ec6f93827cc91b5ff" FOREIGN KEY (tipomaterial)
    REFERENCES public.tipomaterial (idtipomaterial) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.material
    ADD CONSTRAINT "FK_86b962ce86322dbde33aa7f5a0d" FOREIGN KEY (unidadmedida)
    REFERENCES public.unidadmedida (idunidadmedida) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.material
    ADD CONSTRAINT "FK_8bc495bb78ce3a05def060170de" FOREIGN KEY (categoriamaterial)
    REFERENCES public.categoriamaterial (idcategoriamaterial) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento
    ADD CONSTRAINT "FK_392c57953476dc0c328edfc355c" FOREIGN KEY (tipomovimiento)
    REFERENCES public.tipomovimiento (idtipomovimiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento
    ADD CONSTRAINT "FK_f4c153a0c2a17b8eeb581040743" FOREIGN KEY (movimientopersona)
    REFERENCES public.persona (idpersona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.opciones
    ADD CONSTRAINT "FK_5ba3ce93b3a98f7cbad6c5db92f" FOREIGN KEY (id_modulo)
    REFERENCES public.modulos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.permiso
    ADD CONSTRAINT "FK_b7fb539388a477d71be5085e29d" FOREIGN KEY (id_opcion)
    REFERENCES public.opciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT "FK_1f84088983220784529930aad85" FOREIGN KEY (rol)
    REFERENCES public.rol (idrol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT "FK_df8373fcff7fb61cc14be1c9d3b" FOREIGN KEY (ficha)
    REFERENCES public.ficha (idficha) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rol
    ADD CONSTRAINT "FK_ad2f58a8927d0971ce5edf60f06" FOREIGN KEY ("permisosIdpermiso")
    REFERENCES public.permiso (idpermiso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rol_permiso_opcion
    ADD CONSTRAINT "FK_248844427c2d694b66b605d545d" FOREIGN KEY (id_permiso)
    REFERENCES public.permiso (idpermiso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rol_permiso_opcion
    ADD CONSTRAINT "FK_8dfd596f3f5f33748e8fd07221b" FOREIGN KEY (id_opcion)
    REFERENCES public.opciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rol_permiso_opcion
    ADD CONSTRAINT "FK_facd7375734b9bcf2f1550a51a8" FOREIGN KEY (id_rol)
    REFERENCES public.rol (idrol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sede
    ADD CONSTRAINT "FK_9b865ae7b23b58675fc61528202" FOREIGN KEY (centro)
    REFERENCES public.centro (idcentro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sitio
    ADD CONSTRAINT "FK_5930e73927bc15a95ed3c631a6f" FOREIGN KEY (tipositio)
    REFERENCES public.tipositio (idtipositio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.titulado
    ADD CONSTRAINT "FK_80e54fec48bce2f968f7ca63819" FOREIGN KEY (ficha)
    REFERENCES public.ficha (idficha) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.titulado
    ADD CONSTRAINT "FK_abd54427ef2c62a00f13ed2eec3" FOREIGN KEY (area)
    REFERENCES public.area (idarea) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;